### ISSUE TITLE
Found some inconsistency while profiling

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#164]
I take the advantage fo the issues to share on my action point on profiling.

While working on that I found some minor things that could be improved provided we all agree with this way of implementing.

here is the profiling:
----------------------

The following parameter must be filled in for an accurate optical impairment assessment of paths during path computation. We only focus on those parameters that are needed for impairments computation, but other parameters may also be mandatory depending on the targeted use cases.

In general, [null] must be reported for mandatory data when it is not known. for example an EDFA must report out-voa = [null] if the amplifier is equipped with an out VOA and that its value is unknown. If it is not equipped, then it should not report out-voa.

1. amplifier OMS-element

must contain a list of amplifier-element. this list can be used to represent parallel (for different frequency range, like multi-band elements) and or cascaded elements (for DGE capable amplifiers). For this purpose stage order and frequency-range are needed. amplifier-elements categories:

a. EDFA amplifier must contain:

- type-variety (if different or more precise than the one at amplifier level)
- frequency-range
- stage-order is mandatory if there are more than one amplifier
element cascaded for the same frequency range
- actual-gain
- tilt-target
- out-voa if the amplifier is equiped with an out-voa
- in-voa if the amplifier is equiped with an in-voa
- total-output-power
- nominal-carrier-power or nominal-power-spectral-density
- pdl

and may contain:
- name

b. Raman amplifier must contain:

- type-variety (if different of more precise than the one at amplifier level)
- frequency-range
- stage-order is mandatory if there are more than one amplifier
cascaded for the same frequency range
- actual-gain
- raman-direction
- raman-pump
- total-output-power
- nominal-carrier-power or nominal-power-spectral-density
- pdl

and may contain:
- name

c. DGE must contain the power targets for each crossing MC

- type-variety
- stage-order
- is-dynamic-gain-equalizer
- media-channel-groups
   - media-channel-group* []
      - media-channels* []
         - flexi-n
         - flexi-m
         - delta-power

and may contain:
- name

2. Fibers oms-element

Loss of fiber spans should be reported as precisely as possible including the detail of connector fosses of lumped losses if they are known. For this purpose the model provides to element categories: fiber and concentratedloss. The layout of lumped losses should be reported thanks to the index order of each OMS-element and fiber must include:
- type-variety
- length
- loss-coef
- total-loss: this must be the result of measurements (e.g. input power - output power measured on both ends thanks to
amplifier power monitor capability)
- conn-in if loss of connector is known
- conn-out if loss of connector is known
- pmd

3. ROADM

profile of impairments per roadm path (express add or drop) is detailed in C Kelly slides
In addition to this, the target equalization powers are reported per link (OMS). These values must be present:
- equalization-mode
- nominal-carrier-power or power-spectral-density: represent the target value 
- media-channel-groups!
   - media-channel-group* []
      - media-channels* []
         - flexi-n
		 - flexi-m
         - delta-power: represents the deviation between the target
		 value and this MC

and here are the issues:
--------------------------
- amplifiers:
   - out-voa and in-voa should be optional
   - type variety should be present and optional at amplifier-element level
 - fibers:
   - total-loss should be used to report computed loss based on measurement. So that inconsistency between computed loss based on loss_coef and length + connector loss means:
       - if total-loss is bigger: that there are unknown lumped loss
       - if total-loss is smaller (deviation larger than the accuracy of OPM) : that there data have an accuracy issue.
     as a result, total-loss should be mandatory for data extraction use case, and optional for synthetic data.
- delta-power should be a ratio in db (I have  open a specific issue for this one as it can be easily corrected)
- extensive ROADM or Transceiver impairment for each ROADM or Transceiver explicit parameters instance in the network might become too verbose on large networks. If the same values are shared among same type of devices (par part-number or even per group of part-numbers), my preference would be to create a catalog at network level and refer to it in the roadm or transceiver instance.

**Comment by sergiobelotti** [comment]
> I take the advantage fo the issues to share on my action point on profiling.
> 
> While working on that I found some minor things that could be improved provided we all agree with this way of implementing.
> 
> ## here is the profiling:
> The following parameter must be filled in for an accurate optical impairment assessment of paths during path computation. We only focus on those parameters that are needed for impairments computation, but other parameters may also be mandatory depending on the targeted use cases.
> 
> In general, [null] must be reported for mandatory data when it is not known. for example an EDFA must report out-voa = [null] if the amplifier is equipped with an out VOA and that its value is unknown. If it is not equipped, then it should not report out-voa.
> 
> 1. amplifier OMS-element
> 
> must contain a list of amplifier-element. this list can be used to represent parallel (for different frequency range, like multi-band elements) and or cascaded elements (for DGE capable amplifiers). For this purpose stage order and frequency-range are needed. amplifier-elements categories:
> 
> a. EDFA amplifier must contain:
> 
> * type-variety (if different or more precise than the one at amplifier level)
> * frequency-range
> * stage-order is mandatory if there are more than one amplifier
>   element cascaded for the same frequency range
> * actual-gain
> * tilt-target
> * out-voa if the amplifier is equiped with an out-voa
> * in-voa if the amplifier is equiped with an in-voa
> * total-output-power
> * nominal-carrier-power or nominal-power-spectral-density
> * pdl
> 
> and may contain:
> 
> * name
> 
> b. Raman amplifier must contain:
> 
> * type-variety (if different of more precise than the one at amplifier level)
> * frequency-range
> * stage-order is mandatory if there are more than one amplifier
>   cascaded for the same frequency range
> * actual-gain
> * raman-direction
> * raman-pump
> * total-output-power
> * nominal-carrier-power or nominal-power-spectral-density
> * pdl
> 
> and may contain:
> 
> * name
> 
> c. DGE must contain the power targets for each crossing MC
> 
> * type-variety
> * stage-order
> * is-dynamic-gain-equalizer
> * media-channel-groups
>   
>   * media-channel-group* []
>     
>     * media-channels* []
>       
>       * flexi-n
>       * flexi-m
>       * delta-power
> 
> and may contain:
> 
> * name
> 
> 2. Fibers oms-element
> 
> Loss of fiber spans should be reported as precisely as possible including the detail of connector fosses of lumped losses if they are known. For this purpose the model provides to element categories: fiber and concentratedloss. The layout of lumped losses should be reported thanks to the index order of each OMS-element and fiber must include:
> 
> * type-variety
> * length
> * loss-coef
> * total-loss: this must be the result of measurements (e.g. input power - output power measured on both ends thanks to
>   amplifier power monitor capability)
> * conn-in if loss of connector is known
> * conn-out if loss of connector is known
> * pmd
> 
> 3. ROADM
> 
> profile of impairments per roadm path (express add or drop) is detailed in C Kelly slides In addition to this, the target equalization powers are reported per link (OMS). These values must be present:
> 
> * equalization-mode
> * nominal-carrier-power or power-spectral-density: represent the target value
> * media-channel-groups!
>   
>   * media-channel-group* []
>     
>     * media-channels* []
>       
>       * flexi-n
>       * flexi-m
>       * delta-power: represents the deviation between the target
>         value and this MC
> 
> ## and here are the issues:
> * amplifiers:
>   
>   * out-voa and in-voa should be optional
>   * type variety should be present and optional at amplifier-element level
> * fibers:
>   
>   * total-loss should be used to report computed loss based on measurement. So that inconsistency between computed loss based on loss_coef and length + connector loss means:
>     
>     * if total-loss is bigger: that there are unknown lumped loss
>     * if total-loss is smaller (deviation larger than the accuracy of OPM) : that there data have an accuracy issue.
>       as a result, total-loss should be mandatory for data extraction use case, and optional for synthetic data.
> * delta-power should be a ratio in db (I have  open a specific issue for this one as it can be easily corrected)
> * extensive ROADM or Transceiver impairment for each ROADM or Transceiver explicit parameters instance in the network might become too verbose on large networks. If the same values are shared among same type of devices (par part-number or even per group of part-numbers), my preference would be to create a catalog at network level and refer to it in the roadm or transceiver instance.

@EstherLerouzic : thanks for important contribution. I have some comments/request for clarification.
"The layout of lumped losses should be reported thanks to the index order of each OMS-element ..", not very clear to me the sentence , could you elaborate a bit?
"profile of impairments per roadm path (express add or drop) is detailed in C Kelly slides"
We need to find a way to reference in some way the slides from Colin , or we need to eliminate this sentence.
Moreover for express path or add/drop there are specific "optional" attributes that we should indicate in the profile , shouldn't we ?

In the part of the issues:
amplifiers:
out-voa and in-voa should be optional 
type variety should be present and optional at amplifier-element level

**SB> ok. About out-voa and In-voa we already exploit PR#160 to update YANG accordingly .**

fibers:
total-loss should be used to report computed loss based on measurement. So that inconsistency between computed loss based on loss_coef and length + connector 

**SB> if my understanding is correct you want to compare total loss as computed loss based on measurement with computed loss given by loss_coeff + length loss + connector loss. Is correct?**
loss means:
if total-loss is bigger: that there are unknown lumped loss
if total-loss is smaller (deviation larger than the accuracy of OPM) : that there data have an accuracy issue.
**SB> is OPM "Optical Power Monitoring"?**
as a result, total-loss should be mandatory for data extraction use case, and optional for synthetic data.
**SB> We haven't defined anywhere what does it mean data extraction vs. synthetic data**

delta-power should be a ratio in db (I have open a specific issue for this one as it can be easily corrected)
**SB> Already fixed**

extensive ROADM or Transceiver impairment for each ROADM or Transceiver explicit parameters instance in the network might become too verbose on large networks. If the same values are shared among same type of devices (par part-number or even per group of part-numbers), my preference would be to create a catalog at network level and refer to it in the roadm or transceiver instance.
**SB> OK, we can discuss the issue at the next call. Do you in mind a proposal?**

**Comment by sergiobelotti** [comment]
This is the proposed text for total-loss by Esther:
"Total loss is used to report loss measured with ingress and egress amplifier power measurement facility (power measured at ingress amplifier output to the fiber span - power measured at egress amplifier input from the fiber span in dB). This measurement may deviate from the computed loss based on length and loss-coef as it includes all loss contributions including possible lumped loss due to imperfect fiber splices, and connector losses. In case total-loss cannot be measured (no power measurement in place), it should not be reported."
