### ISSUE TITLE
do we have a crisp definition of "channel"? if it is of variable width, what is then the "channel power" per AMP if each channel has a different width?

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#39]
do we have a crisp definition of "channel"? if it is of variable width, what is then the "channel power" per AMP if each channel has a different width?

_Originally posted by @ggrammel in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/pull/36#discussion_r501017004_

**Comment by sergiobelotti** [comment]
@ggrammel : what about " the allocated slice of spectrum that contains a modulated communication signal power"  ?

**Comment by ggrammel** [comment]
The point here is to distinguish between a carrier-bandwidth and a "channel". Keep in mind that a "channel" can exist with or without hosting a carrier. Considering that carriers can be slightly off their central frequancy and still need to fit in a "channel" makes it hard to define "channel".  We are probably in agreement that, a channel is a frequency band broad enough to host an expected carrier (the carrier may not be equipped at the point in time of the cannel reservation). But how to define this in a non-ambiguous manner? 
 
The proposed definition would not work because it is based on the presence of a "carrier". The definition neds to be reviewed by optical experts to clarify: what are the conditions requested from a carrier to fit into a channel. think here about frequency variations, signal definition (what is the cut-off between "carrier" and "non-carrier", possibly power variations, guard-bands, ...?

For all practical means, consider the issue of putting two "channels" next to each other. 
1) Either we define the "channel" pretty narrowly around the "modulated communication signal" and add a <to be definded> guard-band between two adjacent channels, to be sure there is no overlap.
2) or we define "channel" a little wider such that two "channels" can be put right next to each other. In this case we probably have to assume that adjacent channels work in the same target power range and use a similar modulation to get the definition right.

I prefer a definition that is measurable and allows putting "channels" side-by-side (option 2) without additional guard-band. However that may be too much of a limitation for some schemes to work, because those want to nudge carriers closer to each other and to do that a (possibly negative) guard band would be useful and better served with option 1.

**Comment by sergiobelotti** [comment]
> The point here is to distinguish between a carrier-bandwidth and a "channel". Keep in mind that a "channel" can exist with or without hosting a carrier. Considering that carriers can be slightly off their central frequancy and still need to fit in a "channel" makes it hard to define "channel". We are probably in agreement that, a channel is a frequency band broad enough to host an expected carrier (the carrier may not be equipped at the point in time of the cannel reservation). But how to define this in a non-ambiguous manner?
> 
> The proposed definition would not work because it is based on the presence of a "carrier". The definition neds to be reviewed by optical experts to clarify: what are the conditions requested from a carrier to fit into a channel. think here about frequency variations, signal definition (what is the cut-off between "carrier" and "non-carrier", possibly power variations, guard-bands, ...?
> 
> For all practical means, consider the issue of putting two "channels" next to each other.
> 
> 1. Either we define the "channel" pretty narrowly around the "modulated communication signal" and add a  guard-band between two adjacent channels, to be sure there is no overlap.
> 2. or we define "channel" a little wider such that two "channels" can be put right next to each other. In this case we probably have to assume that adjacent channels work in the same target power range and use a similar modulation to get the definition right.
> 
> I prefer a definition that is measurable and allows putting "channels" side-by-side (option 2) without additional guard-band. However that may be too much of a limitation for some schemes to work, because those want to nudge carriers closer to each other and to do that a (possibly negative) guard band would be useful and better served with option 1.

If your

**Comment by sergiobelotti** [comment]
Closed based on the discussion during the weekly call on April 6th https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/commit/9c11a8e09aa885d4f2693d35a4918937f8a798fc,
and open specific issue #69
