### ISSUE TITLE
comment on the minutes 

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#44]
I have read the minutes [minutes-2020-12-15](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/master/minutes/minutes-2020-12-15.md) with the decision to impose implicit range on explicit modes:
"Gert commented on the need to have consistent behaviour with ITU-T application code. ITU-T AC does not consent to provide explict parameters values that can be outside (so more larger) of the range provided by the implicit parameter in the specification. So it was required to add a sentence in the text "highlighting that in case explcit attributes values are provided in addition to the operational modes including these attribute values implicitly, these attributes values should stay in the range limitation determined by the implicit attributes".

I thought that the aim of adding a reference to an application code in the explicit mode, was indeed to enable the explicit mode to work outside the range of the application code (being better than the AC). With this restriction, the explicit mode MUST always have worst performances. This will be a restriction for me as an operator: I buy a product with a wider range but can not operate it on this range because it can not be advertised ?

**Comment by ggrammel** [comment]
Hi Esther,

I re-read the sentence and now notice that the context isn’t clear. We discussed the “Standard Mode” and how it relates to an “Organizational Mode”. Apparently there is a need to add explicit parameters to the “Standard mode” as well i.e. the same set as for “Organizational Mode”. So the sentence you refer to: "highlighting that in case explicit attributes values are provided in addition to the operational modes including these attribute values implicitly, these attributes values should stay in the range limitation determined by the implicit attributes" relates to the explicit parameters added to Application Code/Organizational Mode. The “explicit mode” hasn’t been discussed on the call.

Gert

**Comment by EstherLerouzic** [comment]
Then I have the same comment: why this restriction ? I buy a pair of devices which iare compliant to a given operational mode but have a wider range, but I could not use them on this wide  range ? this does not make sense to me

**Comment by sergiobelotti** [comment]
It is correct what Gert said above "The “explicit mode” hasn’t been discussed on the call", but, on the other hand, reading Esther's comment  I completely agree with her that is a nonsense the restriction we put last time. Probably we need to better understand if behind Application code behavior there is something we did not get correctly, but for organizational mode and explicit mode what Esther said has a perfect sense to me.

**Comment by sergiobelotti** [comment]
> Then I have the same comment: why this restriction ? I buy a pair of devices which iare compliant to a given operational mode but have a wider range, but I could not use them on this wide range ? this does not make sense to me

It is correct what Gert said above "The “explicit mode” hasn’t been discussed on the call", but, on the other hand, reading Esther's comment I completely agree with her that is a nonsense the restriction we put last time. Probably we need to better understand if behind Application code behavior there is something we did not get correctly, but for organizational mode and explicit mode what Esther said has a perfect sense to me.

**Comment by italobusi** [comment]
I think the issue is about interoperability.

A given standard application code guarantees interoperability within a defined frequency range.
Operating a transceiver outside of that range goes beyond the standard definition and it does not guarantee interoperability.

The current YANG does not preclude operating the transceiver outside of the standard range.
One possibility is to use the explicit mode which supports that application code but supports a wider frequency range can be used instead of the application code.
Another possibility is to define an organizational mode  (e.g., vendor-specific) which can operate over the wider frequency range. Whether and how this organizational mode can ensure interoperability is one of the concerns we are discussing in open issue #43.

For an organizational mode, the discussion is a bit more complex since it depends on the level of interoperability the mode is intended to provide.
Operational modes that intend to guarantee interoperability (e.g., vendor-specific or done as a result of a joint engineering between few vendors) should follow the same logic as the standard application code. 
Operational modes that intend to be more liberal can just not put any implicit constraints on the frequency range being used.

**Comment by sergiobelotti** [comment]
closed with new text proposed by Dieter in section 2.5.2, see  https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/43#issuecomment-758057447
